### ISSUE TITLE
How to deal with isort?

### ISSUE THREAD

**Issue by bersbersbers** [LucaCappelletti94/silence_tensorflow#1]
The new version of `silence_tensorflow` is hard to use with `isort` for two reasons.
1. `from` `import`s are moved behind non-`from` `import`s
2. commands are moved behind all imports.

Consequently, `silence_tensorflow()` is called after `import tensorflow as tf`.

What best  to do here?

```
user@host:~> cat bug.py
from silence_tensorflow import silence_tensorflow
silence_tensorflow()
import tensorflow as tf

print("Hello, world!")

user@host:~> isort bug.py
Fixing /home/user/cia/bug.py

user@host:~> cat bug.py
import tensorflow as tf
from silence_tensorflow import silence_tensorflow

silence_tensorflow()

print("Hello, world!")
```

**Comment by LucaCappelletti94** [comment]
Hi @bersbersbers!

I can add a module such as: 

```python
import silence_tensorflow.auto
```
Which automatically would apply the silencing.

What do you think?

**Comment by LucaCappelletti94** [comment]
This would not, however, fix eventual imports that include TensorFlow that are alphabetically sorted before it, such as [horovod](https://github.com/horovod/horovod). Do you have any idea on how we could deal with those? Other than renaming the package something like "aaaaaaaaaaa_silence_plz".

**Comment by bersbersbers** [comment]
Hi @LucaCappelletti94 

> I can add a module such as:
> 
> ```python
> import silence_tensorflow.auto
> ```

This does make sense to me. Of course, this will still trigger a W0611 (as it did before the latest version), but I would be perfectly fine with using
```
import silence_tensorflow.auto  # noqa # pylint: disable=unused-import
```
Maybe `auto` could be something more telling such as `on_import` or `silence_on_import` or something; maybe there even is a naming scheme for this (although I kind of doubt it, since, well, W0611 and articles such as https://chrismorgan.info/blog/say-no-to-import-side-effects-in-python/).

> This would not, however, fix eventual imports that include TensorFlow that are alphabetically sorted before it, such as [horovod](https://github.com/horovod/horovod). Do you have any idea on how we could deal with those? Other than renaming the package something like "aaaaaaaaaaa_silence_plz".

I fortunately did not have that problem yet. All packages that rely on tensorflow are custom packages for me, so they are sorted in a separate section anyway.

**Comment by bersbersbers** [comment]
> Do you have any idea on how we could deal with those? Other than renaming the package something like "aaaaaaaaaaa_silence_plz".

May `# isort:skip` can help (but I could not get it to work with `silence_tensorflow()`).

**Comment by LucaCappelletti94** [comment]
Yep, I tried to conform to the trend of no-side-effects on import, hence the new version.

If that's ok for you I would stick to 'auto' as a few other packages I use have a similar tradeoff.

**Comment by LucaCappelletti94** [comment]
I have added the submodule and updated the readme. If you can give it a read and give me feedback I can then publish the new version if everything checks out!

**Comment by bersbersbers** [comment]
Looks fine in general!

Not sure about whether it is `unused-import` or `unused-variable`, but you probably tested that.

```
import silence_tensorflow.auto # noqa # pylint: disable=unused-import
```
I would write two spaces before the first `#`:
```
import silence_tensorflow.auto  # comment
```
otherwise, `pylint` will have something to say about that, too. Also, note that `# noqa` is not strictly required for `pylint`: `# pylint: disable=unused-xxx` should be enough. I use `# noqa` for other linters that do not allow per-warning suppression (I don't remember which one, though); maybe you can specify that in the readme.

**Comment by LucaCappelletti94** [comment]
Ok, now everything checks out?

**Comment by bersbersbers** [comment]
Haven't tried the code yet, but looks fine for me. "differnt" --> "different".

**Comment by LucaCappelletti94** [comment]
Fixed typo!

**Comment by LucaCappelletti94** [comment]
And published!
