### ISSUE TITLE
Tensorflow 1.15.3 warnings keep coming up

### ISSUE THREAD

**Issue by BigNerd** [LucaCappelletti94/silence_tensorflow#2]
I have put the two lines 
`from silence_tensorflow import silence_tensorflow`
`silence_tensorflow()`
at the top of the main module my Python codes starts with and still I get the ususal Tensorflow warnings such as
`DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  tensor_proto.tensor_content = nparray.tostring()`

I am using Python 3.7 with
tensorflow==1.15.3
Keras==2.3.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2

**Comment by LucaCappelletti94** [comment]
Hi! Do you have a way to setup a Colab that reproduces this? Also, consider that this tool removes all the warnings produced by tensorflow, and this one may be produced just by raising the old-style DeprecationWarning.

Thanks!

**Comment by BigNerd** [comment]
Thanks! I understand the warnings that keep coming up are not covered by the suppression as they do not come from tensorflow, they are just about the tensorflow code and come from the Python interpreter.
**Example:**
`DeprecationWarning: the imp module is deprecated in favour of importlib`
comes from tensorflow_core/python/pywrap_tensorflow_internal.py:15
which is nothing but this line: "import imp".
