### ISSUE TITLE
Not suppressing a tflite info message

### ISSUE THREAD

**Issue by Hussain-Aziz** [LucaCappelletti94/silence_tensorflow#4]
python version: 3.10.13
silence_tensorflow version: 1.2.1
tensorflow version: 2.14.0

When I run a tflite model it doesn't suppress this message `INFO: Created TensorFlow Lite XNNPACK delegate for CPU.`
example: https://gist.github.com/Hussain-Aziz/45b80c63a21bfec98c6ebc9eef1be65c

if you want the example tflite model: [model.zip](https://github.com/LucaCappelletti94/silence_tensorflow/files/14884220/model.zip)

**Comment by LucaCappelletti94** [comment]
Thank you for reporting it - I was almost amazed by how long TensorFlow kept its API stable. Could you kindly include in the issue itself the minimal code example to reproduce it and its dependencies, so that I can easily include it in the test suite and it will be useful for other users in future reference?

**Comment by Hussain-Aziz** [comment]
a minimal example: https://gist.github.com/Hussain-Aziz/45b80c63a21bfec98c6ebc9eef1be65c

if you want, [here](https://github.com/LucaCappelletti94/silence_tensorflow/files/14883996/model.zip) is the model.tflite so you don't have to regenerate it (zip file because github doesn't allow arbitrary binary files)

**Comment by LucaCappelletti94** [comment]
Please edit your issue post to include all of the necessary code in there, otherwise in the future the link may stop working.

**Comment by Hussain-Aziz** [comment]
👍

**Comment by LucaCappelletti94** [comment]
Reproduced.

**Comment by LucaCappelletti94** [comment]
I am afraid [they have left this entirely hardcoded in the C++ part](https://github.com/tensorflow/tensorflow/blob/3570f6d986066b834a7f54f3c3ec60d0245193bd/tensorflow/lite/minimal_logging_ios.cc#L50). The only way to silence that error is to either work directly in C++ and compile against TensorFlow Lite, or recompile the TensorFlow Lite package with the flag changed. You would need to change a line such as the following: https://github.com/tensorflow/tensorflow/issues/58050#issuecomment-1624919480

**Comment by LucaCappelletti94** [comment]
I have added this explanation regarding known corner cases to the README in the new section. Sadly I don't know how to handle it without doing a PR to TensorFlow Lite, and that would be a significant mess by itself.
